baseURL = "https://bizumatica.github.io/"
languageCode = "pt-br"
title = "Bizumática"
theme = "terminal"
publishDir = "docs"
enableEmoji = true

# Ajustes de URL para GitHub Pages (Sempre use false aqui para evitar quebra de CSS)
canonifyURLs = false
relativeURLs = true
removePathAccents = true

[params]
  themeColor = "orange"
  centerTheme = true
  animatedTheme = true
  favicon = "favicon.png"
  customCSS = ["css/extended.css"]

  # Logo Global (Aparece em todas as páginas)
  [params.Logo]
    logoText = "Bizumática"
    logoHomeLink = "/"
    # Esta linha abaixo evita que o texto quebre
    logoCursorStyle = "block"

# Menu Global (Fora do bloco de línguas para não dar erro)
[menu]
  [[menu.main]]
    identifier = "linux"
    name = "Linux"
    url = "/posts"
    weight = 10
  [[menu.main]]
    identifier = "matematica"
    name = "Matemática"
    url = "/matematica"
    weight = 15
  [[menu.main]]
    identifier = "search"
    name = "Buscar"
    url = "/search"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "Sobre"
    url = "/about"
    weight = 25

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\\[', '\\]']]
          inline = [['$', '$'], ['\\(', '\\)']]